name: Build Flutter APK

on:
  push:
    branches:
      - dev_main  # 실제 브랜치 이름 확인!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Generate setting.env from secret
        run: |
          mkdir -p assets
          echo "${{ secrets.SETTING_ENV }}" > assets/setting.env

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
